env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  '@typescript-eslint/explicit-module-boundary-types':
    off
